name: Linux cross compile tests

on:
  push:
    paths-ignore:
      - ".devcontainer/**"
      - ".gitpod.yml"
      - ".vscode/**"
      - "tests/**"
  pull_request:
    paths-ignore:
      - ".devcontainer/**"
      - ".gitpod.yml"
      - ".vscode/**"
      - "tests/**"
  schedule:
    # Run against the last commit on the default branch on Friday at 9pm (UTC?)
    - cron: "0 21 * * 5"

jobs:
  linux-cross:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - target: aarch64-unknown-linux-musl
            rust-version: stable
          - target: i686-unknown-linux-musl
            rust-version: stable
          - target: armv7-unknown-linux-musleabihf
            rust-version: stable
          - target: armv5te-unknown-linux-musleabi
            rust-version: stable

    steps:
      - name: Checkout Mini Moka
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.platform.rust-version }}
          targets: ${{ matrix.platform.target }}

      - name: Install cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: Remove integration tests and force enable rustc_version crate
        run: |
          rm -rf tests
          sed -i '/actix-rt\|async-std\|reqwest/d' Cargo.toml

      - run: cargo clean

      - name: Run tests (sync feature)
        run: |
          cross ${{ matrix.platform.carge-version }} test --release -F sync \
            --target ${{ matrix.platform.target }}
