name: Miri tests

on:
  push:
    paths-ignore:
    - '.devcontainer/**'
    - '.gitpod.yml'
    - '.vscode/**'
    - 'tests/**'
  pull_request:
    paths-ignore:
    - '.devcontainer/**'
    - '.gitpod.yml'
    - '.vscode/**'
    - 'tests/**'
  schedule:
    # Run against the last commit on the default branch on Friday at 9pm (UTC?)
    - cron:  '0 21 * * 5'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Mini Moka
        uses: actions/checkout@v4

      - name: Install Rust nightly toolchain with Miri
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: miri

      - run: cargo clean

      - name: Run Miri test (deque)
        run: cargo miri test deque
